#!/bin/sh
MYDIR="$(dirname $(readlink -f $0))"
export GIO_EXTRA_MODULES="${MYDIR}/sys/lib/gio"
export GST_PLUGIN_PATH_1_0="${MYDIR}/sys/lib/gst"
export GST_REGISTRY_1_0="${MYDIR}/sys/lib/gst/gstreamer-1.0.registry"
export WEBKIT_EXEC_PATH="${MYDIR}/bin"
export WEBKIT_INJECTED_BUNDLE_PATH="${MYDIR}/lib"
export LD_LIBRARY_PATH="${MYDIR}/lib:${MYDIR}/sys/lib"
exec "${MYDIR}/bin/WPEWebDriver" "$@"
